name: Deploy

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
    branches:
      - main
      - develop

env:
  PROJECT_ID: swift-impulse-364410
  REGION: asia-southeast1
  SERVICE: ${{ github.event.repository.name }}-dev
  WORKLOAD_IDENTITY_PROVIDER: projects/657305254360/locations/global/workloadIdentityPools/github-pool/providers/github
  SERVICE_ACCOUNT: github-provider@swift-impulse-364410.iam.gserviceaccount.com

jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "${{ env.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ env.SERVICE_ACCOUNT }}"

      - name: print head_branch
        run: echo ${{ github.event.workflow_run.head_branch }}

      - name: Set env SERVICE
        if: github.event.workflow_run.head_branch == 'main'
        run: echo "SERVICE=${{ github.event.repository.name }}" >> "$GITHUB_ENV"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: "${{ env.SERVICE }}"
          region: "${{ env.REGION }}"
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.SERVICE }}:${{ github.sha }}"

      - name: Show output
        run: |2-
          echo ${{ steps.deploy.outputs.url }}
