name: GitHub Actions Demo

on:
  push:
    branches:
      - "**"

jobs:
  Code-Check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Run CodeRabbit Review
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.CODERABBIT_API_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d '{"event_type": "review"}' \
               https://api.coderabbit.ai/v1/reviews

  Build:
    needs: Code-Check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
      - name: Test needs syntax
        run: echo "This job runs after the Code-Check job"
